export const ACTIONTYPES = {
    REDUX_REDIRECT: "REDUX_REDIRECT",
    REDUX_REDIRECT_CLEAR: "REDUX_REDIRECT_CLEAR",

    DISPOSE_PAGE: "DISPOSE_PAGE",
    DISPOSE_OTHER_PAGES: "DISPOSE_OTHER_PAGES",
    DISPOSE_ALL_PAGES: "DISPOSE_ALL_PAGES",
    
    INIT_HOMEPAGE_STARTED: "INIT_HOMEPAGE_STARTED",

    INIT_CARSPAGE_STARTED: "INIT_CARSPAGE_STARTED",
    INIT_CARSPAGE_SUCCEEDED: "INIT_CARSPAGE_SUCCEEDED",
    INIT_CARSPAGE_FAILED: "INIT_CARSPAGE_FAILED",

    INIT_TASKSPAGE_STARTED: "INIT_TASKSPAGE_STARTED",
    INIT_TASKSPAGE_SUCCEEDED: "INIT_TASKSPAGE_SUCCEEDED",
    INIT_TASKSPAGE_FAILED: "INIT_TASKSPAGE_FAILED",

    INIT_TASKPAGE_STARTED: "INIT_TASKPAGE_STARTED",
    INIT_TASKPAGE_SUCCEEDED: "INIT_TASKPAGE_SUCCEEDED",
    INIT_TASKPAGE_FAILED: "INIT_TASKPAGE_FAILED",

    INIT_TESTPAGE_STARTED: "INIT_TESTPAGE_STARTED",
};